# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'Green Thumb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for greenThumb
  pod 'GoogleMaps'
  pod 'SwiftyJSON', '~> 4.0'
  pod "youtube-ios-player-helper", "~> 1.0.2"
end
